// <auto-generated />
using System;
using Airline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airline.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260330174711_finnal")]
    partial class finnal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airline.Models.Baggage", b =>
                {
                    b.Property<int>("BaggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("baggage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaggageId"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight");

                    b.HasKey("BaggageId");

                    b.HasIndex("TicketId");

                    b.ToTable("Baggage", (string)null);

                    b.HasData(
                        new
                        {
                            BaggageId = 1,
                            Price = 200000m,
                            TicketId = 1,
                            Weight = 20.00m
                        },
                        new
                        {
                            BaggageId = 2,
                            Price = 250000m,
                            TicketId = 2,
                            Weight = 25.00m
                        },
                        new
                        {
                            BaggageId = 3,
                            Price = 300000m,
                            TicketId = 3,
                            Weight = 30.00m
                        },
                        new
                        {
                            BaggageId = 4,
                            Price = 350000m,
                            TicketId = 4,
                            Weight = 35.00m
                        },
                        new
                        {
                            BaggageId = 5,
                            Price = 150000m,
                            TicketId = 5,
                            Weight = 15.00m
                        });
                });

            modelBuilder.Entity("Airline.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("booking_date");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("booking_type");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex(new[] { "UserId" }, "idx_booking_user");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingDate = new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingType = "ONEWAY",
                            ScheduleId = 1,
                            Status = "ACTIVE",
                            UserId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            BookingDate = new DateTime(2026, 3, 20, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            BookingType = "ROUNDTRIP",
                            ScheduleId = 2,
                            Status = "ACTIVE",
                            UserId = 2
                        },
                        new
                        {
                            BookingId = 3,
                            BookingDate = new DateTime(2026, 3, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            BookingType = "ONEWAY",
                            ScheduleId = 3,
                            Status = "ACTIVE",
                            UserId = 3
                        },
                        new
                        {
                            BookingId = 4,
                            BookingDate = new DateTime(2026, 3, 20, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            BookingType = "ONEWAY",
                            ScheduleId = 4,
                            Status = "ACTIVE",
                            UserId = 4
                        },
                        new
                        {
                            BookingId = 5,
                            BookingDate = new DateTime(2026, 3, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingType = "ROUNDTRIP",
                            ScheduleId = 5,
                            Status = "ACTIVE",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Airline.Models.BookingPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("PromoId")
                        .HasColumnType("int")
                        .HasColumnName("promo_id");

                    b.HasKey("Id");

                    b.HasIndex("PromoId");

                    b.HasIndex(new[] { "BookingId", "PromoId" }, "uq_booking_promo")
                        .IsUnique();

                    b.ToTable("BookingPromotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            PromoId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            PromoId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            PromoId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            PromoId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            PromoId = 5
                        });
                });

            modelBuilder.Entity("Airline.Models.Cities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Ho Chi Minh City",
                            Country = "Vietnam"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Hanoi",
                            Country = "Vietnam"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Da Nang",
                            Country = "Vietnam"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Singapore",
                            Country = "Singapore"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Bangkok",
                            Country = "Thailand"
                        });
                });

            modelBuilder.Entity("Airline.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("flight_number");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.HasKey("FlightId");

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            FlightNumber = "VN1001",
                            RouteId = 1
                        },
                        new
                        {
                            FlightId = 2,
                            FlightNumber = "VN1002",
                            RouteId = 2
                        },
                        new
                        {
                            FlightId = 3,
                            FlightNumber = "VN2001",
                            RouteId = 3
                        },
                        new
                        {
                            FlightId = 4,
                            FlightNumber = "VN3001",
                            RouteId = 4
                        },
                        new
                        {
                            FlightId = 5,
                            FlightNumber = "VN4001",
                            RouteId = 5
                        });
                });

            modelBuilder.Entity("Airline.Models.FlightSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_time");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("int")
                        .HasColumnName("available_seats");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime")
                        .HasColumnName("departure_time");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("ScheduleId");

                    b.HasIndex("FlightId");

                    b.HasIndex(new[] { "DepartureTime" }, "idx_schedule_time");

                    b.ToTable("FlightSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            ArrivalTime = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 39,
                            DepartureTime = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 1,
                            Status = "SCHEDULED",
                            TotalSeats = 40
                        },
                        new
                        {
                            ScheduleId = 2,
                            ArrivalTime = new DateTime(2026, 4, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 39,
                            DepartureTime = new DateTime(2026, 4, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 2,
                            Status = "SCHEDULED",
                            TotalSeats = 40
                        },
                        new
                        {
                            ScheduleId = 3,
                            ArrivalTime = new DateTime(2026, 4, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 39,
                            DepartureTime = new DateTime(2026, 4, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 3,
                            Status = "SCHEDULED",
                            TotalSeats = 40
                        },
                        new
                        {
                            ScheduleId = 4,
                            ArrivalTime = new DateTime(2026, 4, 4, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 39,
                            DepartureTime = new DateTime(2026, 4, 4, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 4,
                            Status = "SCHEDULED",
                            TotalSeats = 40
                        },
                        new
                        {
                            ScheduleId = 5,
                            ArrivalTime = new DateTime(2026, 4, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 39,
                            DepartureTime = new DateTime(2026, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 5,
                            Status = "SCHEDULED",
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("Airline.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PassengerType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("passenger_type");

                    b.HasKey("PassengerId");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerId = 1,
                            BookingId = 1,
                            FullName = "Nguyen Van An",
                            PassengerType = "ADULT"
                        },
                        new
                        {
                            PassengerId = 2,
                            BookingId = 2,
                            FullName = "Tran Van Binh",
                            PassengerType = "ADULT"
                        },
                        new
                        {
                            PassengerId = 3,
                            BookingId = 3,
                            FullName = "Le Thi Chi",
                            PassengerType = "ADULT"
                        },
                        new
                        {
                            PassengerId = 4,
                            BookingId = 4,
                            FullName = "Pham Thi Dung",
                            PassengerType = "ADULT"
                        },
                        new
                        {
                            PassengerId = 5,
                            BookingId = 5,
                            FullName = "Vo Van Em",
                            PassengerType = "ADULT"
                        });
                });

            modelBuilder.Entity("Airline.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_status");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_no");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 1400000m,
                            BookingId = 1,
                            PaymentDate = new DateTime(2026, 3, 20, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPAY",
                            PaymentStatus = "PAID",
                            TransactionNo = "TXN000001"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 2050000m,
                            BookingId = 2,
                            PaymentDate = new DateTime(2026, 3, 20, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "MOMO",
                            PaymentStatus = "PAID",
                            TransactionNo = "TXN000002"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 4800000m,
                            BookingId = 3,
                            PaymentDate = new DateTime(2026, 3, 20, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CREDIT_CARD",
                            PaymentStatus = "PAID",
                            TransactionNo = "TXN000003"
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 6850000m,
                            BookingId = 4,
                            PaymentDate = new DateTime(2026, 3, 20, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "BANKING",
                            PaymentStatus = "PAID",
                            TransactionNo = "TXN000004"
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 1650000m,
                            BookingId = 5,
                            PaymentDate = new DateTime(2026, 3, 20, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CASH",
                            PaymentStatus = "PAID",
                            TransactionNo = "TXN000005"
                        });
                });

            modelBuilder.Entity("Airline.Models.Promotion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int")
                        .HasColumnName("discount_percent");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("promo_code");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("PromoId");

                    b.HasIndex("PromoCode")
                        .IsUnique()
                        .HasFilter("[promo_code] IS NOT NULL");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            PromoId = 1,
                            DiscountPercent = 10,
                            EndDate = new DateOnly(2026, 4, 30),
                            PromoCode = "NEWUSER10",
                            StartDate = new DateOnly(2026, 4, 1)
                        },
                        new
                        {
                            PromoId = 2,
                            DiscountPercent = 15,
                            EndDate = new DateOnly(2026, 5, 31),
                            PromoCode = "SUMMER15",
                            StartDate = new DateOnly(2026, 5, 1)
                        },
                        new
                        {
                            PromoId = 3,
                            DiscountPercent = 20,
                            EndDate = new DateOnly(2026, 6, 10),
                            PromoCode = "VIP20",
                            StartDate = new DateOnly(2026, 4, 10)
                        },
                        new
                        {
                            PromoId = 4,
                            DiscountPercent = 12,
                            EndDate = new DateOnly(2026, 6, 30),
                            PromoCode = "HOLIDAY12",
                            StartDate = new DateOnly(2026, 6, 1)
                        },
                        new
                        {
                            PromoId = 5,
                            DiscountPercent = 8,
                            EndDate = new DateOnly(2026, 4, 20),
                            PromoCode = "FLASH8",
                            StartDate = new DateOnly(2026, 4, 15)
                        });
                });

            modelBuilder.Entity("Airline.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<int>("ArrivalCity")
                        .HasColumnType("int")
                        .HasColumnName("arrival_city");

                    b.Property<int>("DepartureCity")
                        .HasColumnType("int")
                        .HasColumnName("departure_city");

                    b.HasKey("RouteId");

                    b.HasIndex("ArrivalCity");

                    b.HasIndex("DepartureCity");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            ArrivalCity = 2,
                            DepartureCity = 1
                        },
                        new
                        {
                            RouteId = 2,
                            ArrivalCity = 3,
                            DepartureCity = 2
                        },
                        new
                        {
                            RouteId = 3,
                            ArrivalCity = 4,
                            DepartureCity = 1
                        },
                        new
                        {
                            RouteId = 4,
                            ArrivalCity = 5,
                            DepartureCity = 4
                        },
                        new
                        {
                            RouteId = 5,
                            ArrivalCity = 1,
                            DepartureCity = 3
                        });
                });

            modelBuilder.Entity("Airline.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("AVAILABLE")
                        .HasColumnName("seat_status");

                    b.HasKey("SeatId");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "ScheduleId", "SeatNumber" }, "UQ_Seats_Schedule_SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            ClassId = 1,
                            ScheduleId = 1,
                            SeatNumber = "A01",
                            SeatStatus = "BOOKED"
                        },
                        new
                        {
                            SeatId = 2,
                            ClassId = 2,
                            ScheduleId = 2,
                            SeatNumber = "B01",
                            SeatStatus = "BOOKED"
                        },
                        new
                        {
                            SeatId = 3,
                            ClassId = 3,
                            ScheduleId = 3,
                            SeatNumber = "C01",
                            SeatStatus = "BOOKED"
                        },
                        new
                        {
                            SeatId = 4,
                            ClassId = 4,
                            ScheduleId = 4,
                            SeatNumber = "D01",
                            SeatStatus = "BOOKED"
                        },
                        new
                        {
                            SeatId = 5,
                            ClassId = 1,
                            ScheduleId = 5,
                            SeatNumber = "A02",
                            SeatStatus = "BOOKED"
                        });
                });

            modelBuilder.Entity("Airline.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BOOKED")
                        .HasColumnName("status");

                    b.HasKey("TicketId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClassId");

                    b.HasIndex("PassengerId");

                    b.HasIndex(new[] { "SeatId" }, "UX_Tickets_SeatId")
                        .IsUnique()
                        .HasFilter("[seat_id] IS NOT NULL");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            BookingId = 1,
                            ClassId = 1,
                            PassengerId = 1,
                            SeatId = 1,
                            Status = "BOOKED"
                        },
                        new
                        {
                            TicketId = 2,
                            BookingId = 2,
                            ClassId = 2,
                            PassengerId = 2,
                            SeatId = 2,
                            Status = "BOOKED"
                        },
                        new
                        {
                            TicketId = 3,
                            BookingId = 3,
                            ClassId = 3,
                            PassengerId = 3,
                            SeatId = 3,
                            Status = "BOOKED"
                        },
                        new
                        {
                            TicketId = 4,
                            BookingId = 4,
                            ClassId = 4,
                            PassengerId = 4,
                            SeatId = 4,
                            Status = "BOOKED"
                        },
                        new
                        {
                            TicketId = 5,
                            BookingId = 5,
                            ClassId = 1,
                            PassengerId = 5,
                            SeatId = 5,
                            Status = "BOOKED"
                        });
                });

            modelBuilder.Entity("Airline.Models.TicketClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("class_name");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("TicketClasses");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "Economy"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "Premium Economy"
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "Business"
                        },
                        new
                        {
                            ClassId = 4,
                            ClassName = "First"
                        });
                });

            modelBuilder.Entity("Airline.Models.TicketPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("price_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.HasKey("PriceId");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "ScheduleId", "ClassId" }, "uq_schedule_class")
                        .IsUnique();

                    b.ToTable("TicketPrices");

                    b.HasData(
                        new
                        {
                            PriceId = 1,
                            ClassId = 1,
                            Price = 1200000m,
                            ScheduleId = 1
                        },
                        new
                        {
                            PriceId = 2,
                            ClassId = 2,
                            Price = 1800000m,
                            ScheduleId = 2
                        },
                        new
                        {
                            PriceId = 3,
                            ClassId = 3,
                            Price = 4500000m,
                            ScheduleId = 3
                        },
                        new
                        {
                            PriceId = 4,
                            ClassId = 4,
                            Price = 6500000m,
                            ScheduleId = 4
                        },
                        new
                        {
                            PriceId = 5,
                            ClassId = 1,
                            Price = 1500000m,
                            ScheduleId = 5
                        });
                });

            modelBuilder.Entity("Airline.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cccd");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("role");

                    b.Property<int?>("SkyMiles")
                        .HasColumnType("int")
                        .HasColumnName("sky_miles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Cccd")
                        .IsUnique()
                        .HasFilter("[cccd] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Ho Chi Minh City",
                            Age = 25,
                            Cccd = "079201000001",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenan@example.com",
                            FirstName = "Nguyen",
                            Gender = "Male",
                            LastName = "An",
                            Password = "123456",
                            Phone = "0900000001",
                            Role = "USER",
                            SkyMiles = 1200,
                            Username = "nguyenan"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Hanoi",
                            Age = 30,
                            Cccd = "079201000002",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            Email = "tranbinh@example.com",
                            FirstName = "Tran",
                            Gender = "Male",
                            LastName = "Binh",
                            Password = "123456",
                            Phone = "0900000002",
                            Role = "USER",
                            SkyMiles = 850,
                            Username = "tranbinh"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Da Nang",
                            Age = 27,
                            Cccd = "079201000003",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "lechi@example.com",
                            FirstName = "Le",
                            Gender = "Female",
                            LastName = "Chi",
                            Password = "123456",
                            Phone = "0900000003",
                            Role = "USER",
                            SkyMiles = 600,
                            Username = "lechi"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "Singapore",
                            Age = 29,
                            Cccd = "079201000004",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "phamdung@example.com",
                            FirstName = "Pham",
                            Gender = "Female",
                            LastName = "Dung",
                            Password = "123456",
                            Phone = "0900000004",
                            Role = "USER",
                            SkyMiles = 1500,
                            Username = "phamdung"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "Bangkok",
                            Age = 35,
                            Cccd = "079201000005",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "voem@example.com",
                            FirstName = "Vo",
                            Gender = "Male",
                            LastName = "Em",
                            Password = "123456",
                            Phone = "0900000005",
                            Role = "ADMIN",
                            SkyMiles = 3000,
                            Username = "voem"
                        });
                });

            modelBuilder.Entity("Airline.Models.Baggage", b =>
                {
                    b.HasOne("Airline.Models.Ticket", "Ticket")
                        .WithMany("Baggages")
                        .HasForeignKey("TicketId")
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Airline.Models.Booking", b =>
                {
                    b.HasOne("Airline.Models.FlightSchedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .IsRequired();

                    b.HasOne("Airline.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Airline.Models.BookingPromotion", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("BookingId")
                        .IsRequired();

                    b.HasOne("Airline.Models.Promotion", "Promo")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("PromoId")
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("Airline.Models.Flight", b =>
                {
                    b.HasOne("Airline.Models.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Airline.Models.FlightSchedule", b =>
                {
                    b.HasOne("Airline.Models.Flight", "Flight")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("FlightId")
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Airline.Models.Passenger", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Airline.Models.Payment", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Airline.Models.Route", b =>
                {
                    b.HasOne("Airline.Models.Cities", "ArrivalCityNavigation")
                        .WithMany("RouteArrivalCityNavigations")
                        .HasForeignKey("ArrivalCity")
                        .IsRequired();

                    b.HasOne("Airline.Models.Cities", "DepartureCityNavigation")
                        .WithMany("RouteDepartureCityNavigations")
                        .HasForeignKey("DepartureCity")
                        .IsRequired();

                    b.Navigation("ArrivalCityNavigation");

                    b.Navigation("DepartureCityNavigation");
                });

            modelBuilder.Entity("Airline.Models.Seat", b =>
                {
                    b.HasOne("Airline.Models.TicketClass", "Class")
                        .WithMany("Seats")
                        .HasForeignKey("ClassId")
                        .IsRequired();

                    b.HasOne("Airline.Models.FlightSchedule", "Schedule")
                        .WithMany("Seats")
                        .HasForeignKey("ScheduleId")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Airline.Models.Ticket", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .IsRequired();

                    b.HasOne("Airline.Models.TicketClass", "Class")
                        .WithMany("Tickets")
                        .HasForeignKey("ClassId")
                        .IsRequired();

                    b.HasOne("Airline.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .IsRequired();

                    b.HasOne("Airline.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId");

                    b.Navigation("Booking");

                    b.Navigation("Class");

                    b.Navigation("Passenger");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Airline.Models.TicketPrice", b =>
                {
                    b.HasOne("Airline.Models.TicketClass", "Class")
                        .WithMany("TicketPrices")
                        .HasForeignKey("ClassId")
                        .IsRequired();

                    b.HasOne("Airline.Models.FlightSchedule", "Schedule")
                        .WithMany("TicketPrices")
                        .HasForeignKey("ScheduleId")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Airline.Models.Booking", b =>
                {
                    b.Navigation("BookingPromotions");

                    b.Navigation("Passengers");

                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.Cities", b =>
                {
                    b.Navigation("RouteArrivalCityNavigations");

                    b.Navigation("RouteDepartureCityNavigations");
                });

            modelBuilder.Entity("Airline.Models.Flight", b =>
                {
                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("Airline.Models.FlightSchedule", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");

                    b.Navigation("TicketPrices");
                });

            modelBuilder.Entity("Airline.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.Promotion", b =>
                {
                    b.Navigation("BookingPromotions");
                });

            modelBuilder.Entity("Airline.Models.Route", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Airline.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.Ticket", b =>
                {
                    b.Navigation("Baggages");
                });

            modelBuilder.Entity("Airline.Models.TicketClass", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("TicketPrices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
