// <auto-generated />
using System;
using Airline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airline.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airline.Models.Baggage", b =>
                {
                    b.Property<int>("BaggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("baggage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaggageId"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight");

                    b.HasKey("BaggageId")
                        .HasName("PK__Baggage__A3ADEABD204A8216");

                    b.HasIndex("TicketId");

                    b.ToTable("Baggage", (string)null);
                });

            modelBuilder.Entity("Airline.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("booking_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("booking_type");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__5DE3A5B1B40D84DC");

                    b.HasIndex("ScheduleId");

                    b.HasIndex(new[] { "UserId" }, "idx_booking_user");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Airline.Models.BookingPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("PromoId")
                        .HasColumnType("int")
                        .HasColumnName("promo_id");

                    b.HasKey("Id")
                        .HasName("PK__BookingP__3213E83F12FA2D24");

                    b.HasIndex("PromoId");

                    b.HasIndex(new[] { "BookingId", "PromoId" }, "uq_booking_promo")
                        .IsUnique();

                    b.ToTable("BookingPromotions");
                });

            modelBuilder.Entity("Airline.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__031491A8108F3ABA");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Airline.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("flight_number");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.HasKey("FlightId")
                        .HasName("PK__Flights__E3705765D5618590");

                    b.HasIndex("RouteId");

                    b.HasIndex(new[] { "FlightNumber" }, "UQ__Flights__340D78BBA1E73FB5")
                        .IsUnique();

                    b.HasIndex(new[] { "FlightNumber" }, "idx_flight_number");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Airline.Models.FlightSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_time");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("int")
                        .HasColumnName("available_seats");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime")
                        .HasColumnName("departure_time");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("SCHEDULED")
                        .HasColumnName("status");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("ScheduleId")
                        .HasName("PK__FlightSc__C46A8A6F561D2411");

                    b.HasIndex("FlightId");

                    b.HasIndex(new[] { "DepartureTime" }, "idx_schedule_time");

                    b.ToTable("FlightSchedules");
                });

            modelBuilder.Entity("Airline.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PassengerType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("passenger_type");

                    b.HasKey("PassengerId")
                        .HasName("PK__Passenge__037645860F400AFE");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Airline.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_status");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__ED1FC9EA224FCDD7");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Airline.Models.Promotion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int")
                        .HasColumnName("discount_percent");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("promo_code");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("PromoId")
                        .HasName("PK__Promotio__84EB4CA580D9F7A0");

                    b.HasIndex(new[] { "PromoCode" }, "UQ__Promotio__C07E231504162AE1")
                        .IsUnique()
                        .HasFilter("[promo_code] IS NOT NULL");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Airline.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<int>("ArrivalCity")
                        .HasColumnType("int")
                        .HasColumnName("arrival_city");

                    b.Property<int>("DepartureCity")
                        .HasColumnType("int")
                        .HasColumnName("departure_city");

                    b.HasKey("RouteId")
                        .HasName("PK__Routes__28F706FE14AF89ED");

                    b.HasIndex("ArrivalCity");

                    b.HasIndex("DepartureCity");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Airline.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BOOKED")
                        .HasColumnName("status");

                    b.HasKey("TicketId")
                        .HasName("PK__Tickets__D596F96BA4DFBACA");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClassId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Airline.Models.TicketClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("class_name");

                    b.HasKey("ClassId")
                        .HasName("PK__TicketCl__FDF47986BADBED47");

                    b.HasIndex(new[] { "ClassName" }, "UQ__TicketCl__7DC4C39DD30DA225")
                        .IsUnique();

                    b.ToTable("TicketClasses");
                });

            modelBuilder.Entity("Airline.Models.TicketPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("price_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.HasKey("PriceId")
                        .HasName("PK__TicketPr__1681726D46F72854");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "ScheduleId", "ClassId" }, "uq_schedule_class")
                        .IsUnique();

                    b.ToTable("TicketPrices");
                });

            modelBuilder.Entity("Airline.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cccd");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("USER")
                        .HasColumnName("role");

                    b.Property<int?>("SkyMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sky_miles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F99B4C109");

                    b.HasIndex(new[] { "Cccd" }, "UQ__Users__37D42BFAF79CEB57")
                        .IsUnique()
                        .HasFilter("[cccd] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E616469AA4722")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__F3DBC572D8273813")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Airline.Models.Baggage", b =>
                {
                    b.HasOne("Airline.Models.Ticket", "Ticket")
                        .WithMany("Baggages")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK__Baggage__ticket___1F98B2C1");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Airline.Models.Booking", b =>
                {
                    b.HasOne("Airline.Models.FlightSchedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__schedu__04E4BC85");

                    b.HasOne("Airline.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__user_i__03F0984C");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Airline.Models.BookingPromotion", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingPr__booki__1BC821DD");

                    b.HasOne("Airline.Models.Promotion", "Promo")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("PromoId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingPr__promo__1CBC4616");

                    b.Navigation("Booking");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("Airline.Models.Flight", b =>
                {
                    b.HasOne("Airline.Models.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK__Flights__route_i__6E01572D");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Airline.Models.FlightSchedule", b =>
                {
                    b.HasOne("Airline.Models.Flight", "Flight")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK__FlightSch__fligh__74AE54BC");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Airline.Models.Passenger", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Passenger__booki__08B54D69");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Airline.Models.Payment", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__bookin__14270015");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Airline.Models.Route", b =>
                {
                    b.HasOne("Airline.Models.City", "ArrivalCityNavigation")
                        .WithMany("RouteArrivalCityNavigations")
                        .HasForeignKey("ArrivalCity")
                        .IsRequired()
                        .HasConstraintName("fk_route_arr");

                    b.HasOne("Airline.Models.City", "DepartureCityNavigation")
                        .WithMany("RouteDepartureCityNavigations")
                        .HasForeignKey("DepartureCity")
                        .IsRequired()
                        .HasConstraintName("fk_route_dep");

                    b.Navigation("ArrivalCityNavigation");

                    b.Navigation("DepartureCityNavigation");
                });

            modelBuilder.Entity("Airline.Models.Ticket", b =>
                {
                    b.HasOne("Airline.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__booking__0D7A0286");

                    b.HasOne("Airline.Models.TicketClass", "Class")
                        .WithMany("Tickets")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__class_i__0F624AF8");

                    b.HasOne("Airline.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__passeng__0E6E26BF");

                    b.Navigation("Booking");

                    b.Navigation("Class");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Airline.Models.TicketPrice", b =>
                {
                    b.HasOne("Airline.Models.TicketClass", "Class")
                        .WithMany("TicketPrices")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__TicketPri__class__7D439ABD");

                    b.HasOne("Airline.Models.FlightSchedule", "Schedule")
                        .WithMany("TicketPrices")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__TicketPri__sched__7C4F7684");

                    b.Navigation("Class");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Airline.Models.Booking", b =>
                {
                    b.Navigation("BookingPromotions");

                    b.Navigation("Passengers");

                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.City", b =>
                {
                    b.Navigation("RouteArrivalCityNavigations");

                    b.Navigation("RouteDepartureCityNavigations");
                });

            modelBuilder.Entity("Airline.Models.Flight", b =>
                {
                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("Airline.Models.FlightSchedule", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TicketPrices");
                });

            modelBuilder.Entity("Airline.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.Promotion", b =>
                {
                    b.Navigation("BookingPromotions");
                });

            modelBuilder.Entity("Airline.Models.Route", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Airline.Models.Ticket", b =>
                {
                    b.Navigation("Baggages");
                });

            modelBuilder.Entity("Airline.Models.TicketClass", b =>
                {
                    b.Navigation("TicketPrices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airline.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
